ARG GO_VERSION=1.26.3
ARG ALPINE_VERSION=3.22
ARG VERSION=dev
ARG PORT=8080

FROM golang:${GO_VERSION}-alpine${ALPINE_VERSION} AS build

ARG VERSION

WORKDIR /app

RUN apk add --no-cache gcc libc-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -a -installsuffix cgo -o app -ldflags "-X 'main.version=${VERSION}'" ./cmd/

FROM alpine:${ALPINE_VERSION}
ARG PORT

RUN addgroup -g 1001 -S appgroup && \
    adduser -u 1001 -S appuser -G appgroup

RUN apk add --no-cache ca-certificates tzdata
WORKDIR /app

COPY --from=build /app/app /app/app

USER appuser

EXPOSE ${PORT}

CMD ["/app/app"]