name: GO CI/CD pipeline

on:
    push:
        branches: ["main","feaure*","dev"]
        tags: ['v*']
    pull_request: 
        branches: ["main","feaure*","dev"]

jobs:
    ci:
        uses: Mark-Grigorev/central-ci-cd/.github/workflows/go-ci-complete.yml@main
        with:
            go-version: '1.26.2'
            linter-version: 'v2.11.4'
            ubuntu-version: '22.04'
    cd_app:
        needs: ci
        if: startsWith(github.ref, 'refs/tags/v')
        permissions:
            contents: read
            packages: write
        uses: Mark-Grigorev/central-ci-cd/.github/workflows/docker-publish.yml@main
        with:
            image-name: ghcr.io/mark-grigorev/gotanks
            dockerfile: Dockerfile.gotanks
            build-args: VERSION=${{ github.ref_name }}
            user-name: mark-grigorev
        secrets:
            REGISTRY_TOKEN: ${{ secrets.CR_PAT }}